# Based on the official recommendation from Semgrep:
# https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#github-actions

name: Semgrep x semgrep-rules-manager
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - name: Install semgrep-rules-manager
        run: pip install semgrep-rules-manager
      - name: Download additional rules from third-party rules
        run: |
          mkdir /home/semgrep/rules
          semgrep-rules-manager --dir /home/semgrep/rules download
      - run: semgrep ci
        env:
          SEMGREP_RULES: "/home/semgrep/rules"