name: Semgrep x semgrep-rules-manager
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"
jobs:
  semgrep:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - name: Run Semgrep
        uses: ./
